version: "3.0"
services:
  redis:
    image: redis:5-alpine
    volumes:
      - .docker/redis-data:/data
    restart: unless-stopped
  app:
    image: queue-test
    volumes:
      - ./:/app
      - /app/node_modules/
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}" # phần này ta định nghĩa ở file .env nhé
    restart: unless-stopped
    depends_on:
      - redis
